version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postmeeting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: sh -c "npm run dev"

volumes:
  pgdata:
